
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF701EF9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE9DDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF23005C)
val md_theme_light_secondary = Color(0xFF9600D5)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF6D9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF310049)
val md_theme_light_tertiary = Color(0xFFB21473)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E6)
val md_theme_light_onTertiaryContainer = Color(0xFF3D0024)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF100563)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF100563)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFF2EFFF)
val md_theme_light_inverseSurface = Color(0xFF282377)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_checkedTrack = Color(0xFFB99CFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF701EF9)
val md_theme_light_outlineVariant = Color(0xFFCAC4CF)
val md_theme_light_scrim = Color(0xFF000000)


val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF3B0091)
val md_theme_dark_primaryContainer = Color(0xFF5500CB)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_secondary = Color(0xFFE8B3FF)
val md_theme_dark_onSecondary = Color(0xFF500074)
val md_theme_dark_secondaryContainer = Color(0xFF7200A3)
val md_theme_dark_onSecondaryContainer = Color(0xFFF6D9FF)
val md_theme_dark_tertiary = Color(0xFFFFAFD1)
val md_theme_dark_onTertiary = Color(0xFF63003D)
val md_theme_dark_tertiaryContainer = Color(0xFF8B0058)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF100563)
val md_theme_dark_onBackground = Color(0xFFE2DFFF)
val md_theme_dark_surface = Color(0xFF100563)
val md_theme_dark_onSurface = Color(0xFFE2DFFF)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF100563)
val md_theme_dark_inverseSurface = Color(0xFFE2DFFF)
val md_theme_dark_inversePrimary = Color(0xFF701EF9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF6805F2)
